# Generated by Django 3.0.8 on 2020-08-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio_text',
            field=models.TextField(null=True),
        ),
    ]
