# Generated by Django 3.0.8 on 2020-08-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_bio_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio_text',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_img',
        ),
    ]
