# Generated by Django 3.0.8 on 2020-08-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200812_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.URLField(null=True),
        ),
    ]
